### ISSUE TITLE
jshint problems.

### ISSUE THREAD

**Issue by feitian124** [mgenev/how-to-sane#35]
there are much jshint problems of current code base, does anyone working on fix this?
if not i'd like to do it tomorrow.

``` js
server   |    65:10  error  Expected { after 'if' condition                                               curly
server   |    84:8   error  Expected { after 'if' condition                                               curly
server   |   104:33  error  'sails' is not defined                                                        no-undef
server   |   133:6   error  Expected { after 'else'                                                       curly
server   |   159:28  error  'sails' is not defined                                                        no-undef
server   |   172:11  error  Closing curly brace does not appear on the same line as the subsequent block  brace-st
...
```

**Comment by mgenev** [comment]
The reason you are seeing so many of those problems all of a sudden is that I recently added the https://www.npmjs.com/package/sails-hook-eslint by @Globegitter. I haven't yet had a chance to fix them, if you have the time before me, please do!

**Comment by mgenev** [comment]
Please have in mind that, the server/api/blueprint folder is imported into this project from https://github.com/mphasize/sails-generate-ember-blueprints.
So it would make more sense to fix the linting errors as a pull request into that project and re-import, otherwise if I ever have to update the blueprint to a newer version, it would break again...

There is also the issue that sails-generate-ember-blueprints has since upgraded to a new version which I'm not sure if @mphasize has released NPM.

@mphasize can you please advise what you thinking about this linting and the new version of the blueprint?

**Comment by IanVS** [comment]
It seems to me that any code which is imported into the project from blueprints should be excluded from linting.  The reason is that everyone has their own coding style and standards, and there's no way that sails-generate-ember-blueprints can conform to all of them.  It would be better to either ignore the generated code or change all errors to warnings for those files, in case someone wants to take the time to go back through and change the generated code to the style in their project.

**Comment by mgenev** [comment]
@IanVS I agree. This does pose the question of how we treat the blueprint folder, which is initially generated by another project, but is then likely added on to by the dev...

**Comment by Globegitter** [comment]
@mgenev you can easily exclude folders via a `.eslintignore` in the `server` folder.

**Comment by mgenev** [comment]
Ok, I'll do that for the blueprints right now, they do include a little bit of my own code, but it's small and experimental so i'll let it slide.

**Comment by feitian124** [comment]
hi guys, seems there are upstream problems. if so i think we'd better add them to .eslintignore and waiting their updates, or contribute there.

**Comment by mgenev** [comment]
I did. Ignoring blueprints now
